### ISSUE TITLE
Merged these patches for homebrew formula espeak

### ISSUE THREAD

**Issue by danielbair** [pettarin/espeakosx#2]
FYI, I have merged these patches to the homebrew espeak to also compile and install libespeak.
I've submitted a pull request against the espeak.rb formula, but now homebrew maintainers are considering dropping espeak from their official formula list. See https://github.com/Homebrew/homebrew-core/pull/2726
So it may be necessary to use my homebew tap from now on.
Add the tap:
`brew tap danielbair/tap`
Then install as any other formula:
`brew install danielbair/tap/espeak`

**Comment by pettarin** [comment]
Thank you for letting me know, that's great!

I added a note about it in the README.

Closing.
